# Generated by Django 4.2.7 on 2023-12-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='website_link',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
